#!/bin/bash
# determine_quality_distribution 0.0.1
# Generated by dx-app-wizard.

main() {

  echo "Value of reads: '$reads'"
  echo "Value of read_mates: '$read_mates'"

  set -x

  #if [[ "${num_reads_per_chunk}" == "" ]]; then
  #  NUM_LANES=300000000 # 5X WGS per chunck (w/ ~200 bp per reads), ~75 million reads per chunck, ~300 million lines per chunck
  #else
  NUM_LANES=$(( num_reads_per_chunk * 4 ))
  #fi

  dx download "${reads}" -o - | zcat | split -l ${NUM_LANES} -d --additional-suffix="_1.fastq" - --filter='gzip > $FILE.gz' reads_prefix_ &
  dx download "${read_mates}" -o - | zcat | split -l ${NUM_LANES} -d --additional-suffix="_2.fastq" - --filter='gzip > $FILE.gz' reads_prefix_ &

  wait

  touch read_prefix.txt
  for left_read in reads_prefix_*_1.fastq.gz; do
    echo ${left_read%_1.fastq.gz} >> read_prefix.txt
  done

  cat "read_prefix.txt" | xargs -n1 -P$(nproc) -I '{}' python /get_error_prob.py --reads '{}'_1.fastq.gz --mates '{}'_2.fastq.gz --output-quality-score-file '{}'_errorprob.txt.gz

  ls *_errorprob.txt.gz
  zcat *_errorprob.txt.gz | awk 'BEGIN{FS= "\t"; bases=0; delta=0; avg=0; mean2=0;}{delta = $1 - avg; avg += delta / NR; mean2 += delta * ($1 - avg); bases += $2;} END { print avg >> "mean_pair_qualities.txt"; print sqrt(mean2 / (NR-1)) >> "standard_deviation_pair_qualities.txt";  print bases >> "total_reads.txt"}'

  mean_pair_qualities=$(cat "mean_pair_qualities.txt")
  standard_deviation_pair_qualities=$(cat "standard_deviation_pair_qualities.txt")
  total_reads=$(cat "total_reads.txt")
  coverage=$(awk -v total_reads="$total_reads" -v captured_size="$captured_size_in_bp" 'BEGIN{printf "%.4f\n", (total_reads/captured_size)}')
  dx-jobutil-add-output mean_pair_qualities "$mean_pair_qualities" --class=float
  dx-jobutil-add-output standard_deviation_pair_qualities "$standard_deviation_pair_qualities" --class=float
  dx-jobutil-add-output coverage "$coverage" --class=float
}
